config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :home, only: [:index]
  resources :items
  resources :purchases
  resources :users, only: [:show, :index]



end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    alias_action :create, :update, :destroy, :read, :to => :crud

      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.id != nil
        can :read, :all
        can :crud, Item, user_id: user.id
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :purchases

  validates :name, presence: true
  validates :regular_price, presence: true
  validates :sale_price, presence: true

  validates :name, uniqueness: true

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :items

  validates :name, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :purchases
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @items = Item.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
    @purchases = Purchase.order(params[:sort_purchase])
  end

  private
  def sort_column
    Item.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  load_and_authorize_resource param_method: :item_params

  def index

  end

  def show

  end

  def new

  end

  def create
    if @item.save
      flash[:notice] = "Item Saved"
      render :show
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @item.update(item_params)
      flash[:notice] = "Item Updated"
      render :show
    else
      render :edit
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    @items = Item.all
    flash[:notice] = "Item Deleted"
    render :index

  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :user_id, :regular_price, :sale_price)
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

    load_and_authorize_resource param_method: :purchase_params

    def index
      respond_to do |format|
        format.html { render :index }
        format.js
      end
    end

    def show

    end

    def new
      @items = Item.all
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end

    def create
      if @purchase.save
        flash[:notice] = "Purchase Saved"
        redirect_to purchase_path(@purchase)
      else
        @items = Item.all
        render :new
      end
    end

    def edit
      @items = Item.all
    end

    def update
      if @purchase.update(purchase_params)
        flash[:notice] = "Purchase Updated"
        render :show
      else
        render :edit
      end
    end

    def destroy
      Purchase.find(params[:id]).destroy
      @purchases = Purchase.all
      flash[:notice] = "Purchase Deleted"
      redirect_to purchases_path
    end

    private
    def purchase_params
      params.require(:purchase).permit(:name, :date, :user_id, {item_ids: []} )
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/views/home/_items.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-striped table-hover table-custom">
  <tr>
    <th> <%= sortable "name" %></th>
    <th> <%= sortable "regular_price" %></th>
    <th> <%= sortable "sale_price" %></th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td>
        <%= number_to_currency(item.regular_price, unit: "$") %>
      </td>
      <td>
        <%= number_to_currency(item.sale_price, unit: "$") %>
      </td>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<div class="col-md-6">
  <h3>Items</h3>
  <%= form_tag home_index_path, method: 'get', id: "items-search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>
<div id="items">
  <%= render 'items' %>
</div>
<%= will_paginate @items %>
</div>
<div class="col-md-6">
  <h3>Purchases</h3>
  <ul class="list-group">
  <% @purchases.each do |purchase| %>
    <%= link_to purchase_path(purchase) do %>
      <li class="list-group-item"><%= purchase.name %></li>
    <% end %>
  <% end %>
  </ul>
</div>

app/views/home/index.js.erb
$('#items').html('<%= j render "items" %>');

app/views/items/_form.html.erb
<%= bootstrap_form_for(@item) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.number_field :regular_price, step: '.01' %>
  <%= f.number_field :sale_price, step: '.01' %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit data: {disable_with: 'I T E M I Z I N G'}, class: "btn btn-block btn-primary"%>
<% end %>

app/views/items/index.html.erb
<h1>Items</h1>
<% if @items.any? %>
  <ul>
    <% @items.each do |item| %>
      <li><%= link_to item.name, item_path(item) %></li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Add a new Item", new_item_path, class: "btn btn-block btn-primary" %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<h1> <%= @item.name %> </h1>
<h3> <i>Added by: <%= @item.user.email %></i></h3>
<ul>
  <li><%= @item.description %></li>
  <li><%= @item.regular_price %></li>
  <li><%= @item.sale_price %></li>
</ul>

<% if can? :delete, @item %>
<div class="col-md-4 col-md-offset-4">
  <div class="btn-group btn-group-justified">
    <!-- <div class="btn-block"> -->
      <%= link_to "Edit", edit_item_path(@item), class: "btn btn-warning" %>
      <%= link_to "Delete", item_path(@item), method: :delete, class: "btn btn-danger" %>
  <!-- </div> -->
  </div>
</div>
<% end %>

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-dismisable alert-success text-center" role="alert" style="margin-bottom: 0px;">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-dismisable alert-danger text-center" role="alert" style="margin-bottom: 0px;">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>Amazonee!</strong></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Add a new Item", new_item_path %></li>
        <li><%= link_to "Log a new Purchase", new_purchase_path %></li>
        <li><%= link_to "Browse Items", items_path %></li>
        <li><%= link_to "Browse Purchases", purchases_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <% if current_user.admin? %>
              <span class="orange"><%= current_user.email %></span><span class="caret"></span>
            <% else %>
            <%= current_user.email %><span class="caret"></span>

            <% end %>

          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Profile", user_path(current_user) %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="badge badge-warning"><%=  %></span>
          </a>
        </li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title) %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>

    <%= render 'layouts/alerts' %>

    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/purchases/_form.html.erb
<%= bootstrap_form_for(@purchase) do |f| %>
  <%= f.text_field :name %>
  <% if Item.all.any? %>
  <%= f.collection_check_boxes(:item_ids, @items, :id, :name) %>
  <% else %>
  <p>No items are available.</p>
  <% end %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.datetime_select :date %>
  <%= f.submit data: {disable_with: 'Logging Purchase...'}, class: "btn btn-block btn-primary"%>
<% end %>

app/views/purchases/_remote_form.html.erb
<%= bootstrap_form_for(@purchase) do |f| %>
  <%= f.text_field :name %>
  <% if Item.all.any? %>
    <%= f.collection_check_boxes(:item_ids, @items, :id, :name, class: 'checkbox_container') %>
  <% else %>
  <p>No items are available.</p>
  <% end %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.datetime_select :date %>
  <%= f.submit data: {disable_with: 'Logging Purchase...'}, class: "btn btn-block btn-primary"%>
<% end %>
  <%= link_to "Cancel", purchases_path, class: "btn btn-block btn-info", remote: true %>

app/views/purchases/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

app/views/purchases/index.html.erb
<h1>Purchases</h1>
<% if @purchases.any? %>
  <ul>
    <% @purchases.each do |purchase| %>
      <li><%= link_to purchase.name, purchase_path(purchase) %></li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Add a new Purchase", new_purchase_path, class: "btn btn-block btn-primary", id: "new-purchase-index", remote: true %>
<div id='purchase-form'>

</div>

app/views/purchases/index.js.erb
$('#purchase-form').html("");
$('#new-purchase-index').show();

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

app/views/purchases/new.js.erb
$('#purchase-form').html('<%= j render "remote_form" %>');
$('#new-purchase-index').hide();

app/views/purchases/show.html.erb
<h1> <%= @purchase.name %> </h1>
<h3> <i>Added by: <%= @purchase.user.email %></i></h3>
<ul>
  <% @purchase.items.each do |item| %>
    <li><%= link_to item.name, item_path(item) %></li>
  <% end %>
</ul>

<% if can? :delete, @purchase %>
<div class="col-md-4 col-md-offset-4">
  <div class="btn-group btn-group-justified">
    <%= link_to "Edit", edit_purchase_path(@purchase), class: "btn btn-warning" %>
    <%= link_to "Delete", purchase_path(@purchase), method: :delete, class: "btn btn-danger" %>
  </div>
</div>
<% end %>